// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Data;
using DeliveryDatePlanning.Data.Context;

namespace Dpd.WebApi.Migrations
{
    [DbContext(typeof(AptContext))]
    partial class AptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
           
#pragma warning restore 612, 618
        }
    }
}